import {defineConfig} from 'vite';
import vue from '@vitejs/plugin-vue';
import monkey, {cdn} from 'vite-plugin-monkey';
import Components from 'unplugin-vue-components/vite';
import {AntDesignVueResolver} from "unplugin-vue-components/resolvers";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        vue(),
        Components({
            resolvers: [
                AntDesignVueResolver({
                    importStyle: false, // css in js
                }),
            ],
        }),
        monkey({
            entry: 'src/main.ts',
            userscript: {
                name: 'PtToPtools-Dev',
                icon: 'https://img.ptools.fun/blog/209271688287909_.pic.jpg',
                namespace: 'http://tampermonkey.net/',
                version: '2023.09.06.03',
                author: 'ngfchl',
                description: 'PT站点信息与PTools同步及种子推送到下载器',
                match: [
                    'https://ptchdbits.co/*',
                    'https://www.gamegamept.com/*',
                    'https://www.ptlsp.com/*',
                    'https://ptcafe.club/*',
                    'https://shadowflow.org/*',
                    'https://rousi.zip/*',
                    'https://www.torrentleech.org/*',
                    'https://hd-space.org/*',
                    'https://www.biho.xyz/*',
                    'https://pt.dhtclub.com/*',
                    'https://ubits.club/*',
                    'https://kufei.org/*',
                    'https://pandapt.net/*',
                    'https://www.okpt.net/*',
                    'https://share.ilolicon.com/*',
                    'https://hdfun.me/*',
                    'http://hdfun.me/*',
                    'https://wukongwendao.top/*',
                    'https://1ptba.com/*',
                    'https://52pt.site/*',
                    'https://audiences.me/*',
                    'https://byr.pt/*',
                    'https://ccfbits.org/*',
                    'https://club.hares.top/*',
                    'https://discfan.net/*',
                    'https://et8.org/*',
                    'https://filelist.io/*',
                    'https://hdatmos.club/*',
                    'https://hdchina.org/*',
                    'https://hdcity.leniter.org/*',
                    'https://hdhome.org/*',
                    'https://hdmayi.com/*',
                    'https://hdsky.me/*',
                    'https://hdtime.org/*',
                    'https://hudbt.hust.edu.cn/*',
                    'https://iptorrents.com/t',
                    'https://xp.m-team.io/*',
                    'https://lemonhd.org/*',
                    'https://nanyangpt.com/*',
                    'https://npupt.com/*',
                    'https://ourbits.club/*',
                    'https://pt.btschool.club/*',
                    'https://pt.eastgame.org/*',
                    'https://pt.hdbd.us/*',
                    'https://pt.keepfrds.com/*',
                    'https://pterclub.com/*',
                    'https://pthome.net/*',
                    'https://springsunday.net/*',
                    'https://totheglory.im/*',
                    'https://u2.dmhy.org/*',
                    'https://www.beitai.pt/*',
                    'https://www.haidan.video/userdetails.php?id=*',
                    'https://www.haidan.video/usercp.php',
                    'https://hdarea.club/*',
                    'https://www.hddolby.com/*',
                    'https://www.htpt.cc/*',
                    'https://www.nicept.net/*',
                    'https://www.pttime.org',
                    'https://www.tjupt.org/*',
                    'https://www.torrentleech.org',
                    'https://www.carpet.net/*',
                    'https://wintersakura.net/*',
                    'https://hhanclub.top/*',
                    'https://www.hdpt.xyz/*',
                    'https://ptchina.org/*',
                    'http://www.oshen.win/*',
                    'https://www.hd.ai/*',
                    'http://ihdbits.me/*',
                    'https://zmpt.cc/*',
                    'https://leaves.red/*',
                    'https://piggo.me/*',
                    'https://pt.2xfree.org/*',
                    'https://sharkpt.net/*',
                    'https://www.dragonhd.xyz/*',
                    'https://oldtoons.world/*',
                    'http://hdmayi.com/*',
                    'https://www.3wmg.com/*',
                    'https://carpt.net/*',
                    'https://pt.0ff.cc/*',
                    'https://hdpt.xyz/*',
                    'https://azusa.wiki/*',
                    'https://pt.itzmx.com/*',
                    'https://gamegamept.cn/*',
                    'https://srvfi.top/*',
                    'https://www.icc2022.com/*',
                    'http://leaves.red/*',
                    'https://xingtan.one/*',
                    'http://uploads.ltd/*',
                    'https://cyanbug.net/*',
                    'https://ptsbao.club/*',
                    'https://greatposterwall.com/*',
                    'https://gainbound.net/*',
                    'http://hdzone.me/*',
                    'https://www.pttime.org/*',
                    'https://pt.msg.vg/*',
                    'https://pt.soulvoice.club/*',
                    'https://www.hitpt.com/*',
                    'https://hdfans.org/*',
                    'https://www.joyhd.net/*',
                    'https://hdzone.me/*',
                    'https://reelflix.xyz/*',
                    'https://pt.hdpost.top/*',
                    'https://monikadesign.uk/*',
                    'https://exoticaz.to/*',
                    'https://cinemaz.to/*',
                    'https://avistaz.to/*',
                    'https://iptorrents.com/*',
                    'https://pt.hdupt.com/*',
                    'https://www.oshen.win/*',
                    'https://hdcity.city/*',
                    'https://hdvideo.one/*',
                    'https://chdbits.co/*',
                    'https://kamept.com/*',
                    'https://ultrahd.net/*',
                    'http://pt.tu88.men/*',
                    'https://pt.hd4fans.org/*',
                    'https://hd-torrents.org/*',
                    'https://fsm.name/*',
                    'https://dajiao.cyou/*',
                    'https://hudbt.hust.edu.cn/*',
                    // 'https://zhuque.in/*',
                    'https://dicmusic.com/*',
                    'https://open.cd/*',
                    'https://www.open.cd/*',
                ],
            },
            build: {
                externalGlobals: {
                    vue: cdn.jsdelivr('Vue', 'dist/vue.global.prod.js'),
                },
            },
        }),
    ],
});
